/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataBuku_Controller;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    DataBuku_Controller dataController;
    public MainView() {
        initComponents();
        dataController = new DataBuku_Controller(this);
        dataController.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_dataBuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextJUDUL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextGENRE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextPENULIS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextPENERBIT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextLOKASI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextSTOK = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        show_all = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextSEARCH = new javax.swing.JTextField();
        jComboKATEGORI = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_dataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Judul", "Genre", "Penulis", "Penerbit", "Lokasi", "Stok"
            }
        ));
        table_dataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dataBuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 776, 378));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN SIGMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 44, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 88, -1, -1));

        jTextID.setEditable(false);
        jTextID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 83, 190, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("JUDUL BUKU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 132, -1, -1));

        jTextJUDUL.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextJUDUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 127, 190, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("GENRE BUKU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 176, -1, -1));

        jTextGENRE.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextGENRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 171, 190, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setText("PENULIS BUKU");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 220, -1, -1));

        jTextPENULIS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextPENULIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 215, 190, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("PENERBIT BUKU");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 264, -1, -1));

        jTextPENERBIT.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextPENERBIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 259, 190, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel7.setText("LOKASI BUKU");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 308, -1, -1));

        jTextLOKASI.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextLOKASI, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 303, 190, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel8.setText("STOK BUKU");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 352, -1, -1));

        jTextSTOK.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextSTOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 347, 190, -1));

        add.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        add.setText("TAMBAH");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 156, 50));

        edit.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        edit.setText("UBAH");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 156, 50));

        delete.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        delete.setText("HAPUS");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 156, 50));

        show_all.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        show_all.setText("TAMPILKAN SEMUA");
        show_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_allActionPerformed(evt);
            }
        });
        getContentPane().add(show_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 50));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setText("Cari Buku :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 55, -1, -1));

        jTextSEARCH.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(jTextSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 50, 250, -1));

        jComboKATEGORI.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jComboKATEGORI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Genre", "Penulis", "Penerbit" }));
        getContentPane().add(jComboKATEGORI, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 50, 130, -1));

        search.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        search.setText("CARI");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       dataController.insert();
       dataController.isiTabel();
       clearField();
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        dataController.update();
        dataController.isiTabel();
        clearField();
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        dataController.delete();
        dataController.isiTabel();
        clearField();
    }//GEN-LAST:event_deleteActionPerformed

    private void table_dataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataBukuMouseClicked
        int row = table_dataBuku.getSelectedRow();
        jTextID.setText(table_dataBuku.getValueAt(row, 0).toString());
        jTextJUDUL.setText(table_dataBuku.getValueAt(row, 1).toString());
        jTextGENRE.setText(table_dataBuku.getValueAt(row, 2).toString());
        jTextPENULIS.setText(table_dataBuku.getValueAt(row, 3).toString());
        jTextPENERBIT.setText(table_dataBuku.getValueAt(row, 4).toString());
        jTextLOKASI.setText(table_dataBuku.getValueAt(row, 5).toString());
        jTextSTOK.setText(table_dataBuku.getValueAt(row, 6).toString());
    }//GEN-LAST:event_table_dataBukuMouseClicked

    // Supaya bisa nampilin semua data lagi setelah search
    private void show_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_allActionPerformed
        dataController.isiTabel();
        clearField();
        clearSearchBar();
    }//GEN-LAST:event_show_allActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String kategori = (String) jComboKATEGORI.getSelectedItem();
        String cari = jTextSEARCH.getText();
        dataController.search(kategori, cari);
        clearField();
    }//GEN-LAST:event_searchActionPerformed

    private void clearField(){
        jTextID.setText("");
        jTextJUDUL.setText("");
        jTextGENRE.setText("");
        jTextPENULIS.setText("");
        jTextPENERBIT.setText("");
        jTextLOKASI.setText("");
        jTextSTOK.setText("");
    }
    
    //ini supaya clean aja biar ga ada teks di search bar kalo abis nyari sesuatu terus show all data
    private void clearSearchBar(){
        jTextSEARCH.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox<String> jComboKATEGORI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextGENRE;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextJUDUL;
    private javax.swing.JTextField jTextLOKASI;
    private javax.swing.JTextField jTextPENERBIT;
    private javax.swing.JTextField jTextPENULIS;
    private javax.swing.JTextField jTextSEARCH;
    private javax.swing.JTextField jTextSTOK;
    private javax.swing.JButton search;
    private javax.swing.JButton show_all;
    private javax.swing.JTable table_dataBuku;
    // End of variables declaration//GEN-END:variables

    public JTable getTable_data() {
        return table_dataBuku;
    }

    public void setTable_data(JTable table_dataBuku) {
        this.table_dataBuku = table_dataBuku;
    }

    public JTextField getjTextGENRE() {
        return jTextGENRE;
    }

    public void setjTextGENRE(JTextField jTextGENRE) {
        this.jTextGENRE = jTextGENRE;
    }

    public JTextField getjTextID() {
        return jTextID;
    }

    public void setjTextID(JTextField jTextID) {
        this.jTextID = jTextID;
    }

    public JTextField getjTextJUDUL() {
        return jTextJUDUL;
    }

    public void setjTextJUDUL(JTextField jTextJUDUL) {
        this.jTextJUDUL = jTextJUDUL;
    }

    public JTextField getjTextLOKASI() {
        return jTextLOKASI;
    }

    public void setjTextLOKASI(JTextField jTextLOKASI) {
        this.jTextLOKASI = jTextLOKASI;
    }

    public JTextField getjTextPENERBIT() {
        return jTextPENERBIT;
    }

    public void setjTextPENERBIT(JTextField jTextPENERBIT) {
        this.jTextPENERBIT = jTextPENERBIT;
    }

    public JTextField getjTextPENULIS() {
        return jTextPENULIS;
    }

    public void setjTextPENULIS(JTextField jTextPENULIS) {
        this.jTextPENULIS = jTextPENULIS;
    }

    public JTextField getjTextSTOK() {
        return jTextSTOK;
    }

    public void setjTextSTOK(JTextField jTextSTOK) {
        this.jTextSTOK = jTextSTOK;
    }
    
    
}
